language: objective-c

osx_image: xcode8.2

before_install:
  - brew update
  - brew outdated carthage || brew update carthage
before_script:
  - carthage bootstrap --platform iOS
script: xcodebuild -scheme "GuardedSwiftyJson" -destination "platform=iOS Simulator,name=iPhone 7" test
