language: objective-c

osx_image: xcode8.2

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap --platform iOS
script: xcodebuild -scheme "GuardedSwiftyJson" -destination "platform=iOS Simulator,id=22FA2149-1241-469C-BF6D-462D3837DB72" test
